baseURL = "/"
languageCode = "en-us"
title = "Astrophoenix"
theme = "ananke"
SectionPagesMenu = "main"
#Paginate = 
[params]
        favicon = "/kev.png"
        mastodon = "https://pkm.social/@astrophoenix"
        #github = ""
        #gitlab = ""
        recent_posts_number = 6
        #body_classes = "bg-moon-gray dark-red"
        #mode = "auto"
